services:
  web:
    build: .
    container_name: odrs 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/storage:/storage
    restart: unless-stopped
    network_mode: "host" 
